FuelStation/Models/Tank.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FuelStation.Models
{
    public class Tank
    {
        //ID емкости
        public int TankID { get; set; }
        //Тип емкости
        [Display(Name = "Емкость")]
        public string TankType { get; set; }
        //Вес емкости
        [Display(Name = "Вес")]
        public float TankWeight { get; set; }
        //Объем емкости
        [Display(Name = "Объем")]
        public float TankVolume { get; set; }
        //Материал емкости
        [Display(Name = "Материал")]
        public string TankMaterial { get; set; }
        //ссылка на файл изображения емкости
        [Display(Name = "Изображение")]
        public string TankPicture { get; set; }
        public virtual ICollection<Operation> Operations { get; set; }
        public Tank()
        {
            Operations = new List<Operation>();

        }

    }
}

FuelStation/ViewModels/TanksViewModel.cs
using FuelStation.DataLayer.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FuelStation.ViewModels
{
    public class TanksViewModel
    {
        public IEnumerable<Tank> Tanks { get; set; }

        //Свойство для фильтрации
        //Наименование емкости
        [Display(Name = "Наименование емкости")]
        public string TankType { get; set; }

        //Вес емкости
        [Display(Name = "Вес")]
        public float TankWeight { get; set; }

        //Объем емкости
        [Display(Name = "Объем")]
        public float TankVolume { get; set; }

        //Материал емкости
        [Display(Name = "Материал")]
        public string TankMaterial { get; set; }



        //Свойство для навигации по страницам
        public PageViewModel PageViewModel { get; set; }
        // Порядок сортировки
        public SortViewModel SortViewModel { get; set; }
    }
}

FuelStation/Controllers/TanksController.cs
using FuelStation.DataLayer.Data;
using FuelStation.DataLayer.Models;
using FuelStation.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Linq;
using System.Threading.Tasks;

namespace FuelStation.Controllers
{
    public class TanksController : Controller
    {
        private readonly FuelsContext _context;
        private readonly int pageSize = 10;   // количество элементов на странице 

        public TanksController(FuelsContext context, IConfiguration appConfig = null)
        {
            _context = context;
            if (appConfig != null)
            {
                pageSize = int.Parse(appConfig["Parameters:PageSize"]);
            }
        }

        // GET: Tanks
        public IActionResult Index(string TankType = "", int page = 1)
        {

            // Фильтрация данных
            IQueryable<Tank> fuelsContext = _context.Tanks.Where(t => t.TankType.Contains(TankType ?? ""));

            // Разбиение на страницы
            var count = fuelsContext.Count();
            fuelsContext = fuelsContext.Skip((page - 1) * pageSize).Take(pageSize);

            // Формирование модели для передачи представлению
            TanksViewModel fuels = new()
            {
                Tanks = fuelsContext,
                PageViewModel = new PageViewModel(count, page, pageSize),
                //SortViewModel = new SortViewModel(sortOrder),
                TankType = TankType
            };

            return View(fuels);
        }

        // GET: Tanks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tank = await _context.Tanks
                .SingleOrDefaultAsync(m => m.TankID == id);
            if (tank == null)
            {
                return NotFound();
            }

            return View(tank);
        }

        // GET: Tanks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tanks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TankID,TankType,TankWeight,TankVolume,TankMaterial,TankPicture")] Tank tank)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                _context.Add(tank);
                await _context.SaveChangesAsync();

            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Tanks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tank = await _context.Tanks.SingleOrDefaultAsync(m => m.TankID == id);
            if (tank == null)
            {
                return NotFound();
            }
            return View(tank);
        }

        // POST: Tanks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TankID,TankType,TankWeight,TankVolume,TankMaterial,TankPicture")] Tank tank)
        {
            if (id != tank.TankID)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(tank);
            }
            else
            {
                try
                {
                    _context.Update(tank);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TankExists(tank.TankID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: Tanks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tank = await _context.Tanks
                .SingleOrDefaultAsync(m => m.TankID == id);
            if (tank == null)
            {
                return NotFound();
            }

            return View(tank);
        }

        // POST: Tanks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tank = await _context.Tanks.SingleOrDefaultAsync(m => m.TankID == id);
            _context.Tanks.Remove(tank);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TankExists(int id)
        {
            return _context.Tanks.Any(e => e.TankID == id);
        }
    }
}

FuelStation/Views/Tanks/Create.cshtml
@model Tank

@{
    ViewData["Title"] = "Создать";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавить</h2>

<h4>Емкость</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TankType" class="control-label"></label>
                <input asp-for="TankType" class="form-control" />
                <span asp-validation-for="TankType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankWeight" class="control-label"></label>
                <input asp-for="TankWeight" class="form-control" />
                <span asp-validation-for="TankWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankVolume" class="control-label"></label>
                <input asp-for="TankVolume" class="form-control" />
                <span asp-validation-for="TankVolume" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankMaterial" class="control-label"></label>
                <input asp-for="TankMaterial" class="form-control" />
                <span asp-validation-for="TankMaterial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankPicture" class="control-label"></label>
                <input asp-for="TankPicture" class="form-control" />
                <span asp-validation-for="TankPicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FuelStation/Views/Tanks/Delete.cshtml
@model Tank

@{
    ViewData["Title"] = "Удалить";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <h4>Емкость</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TankType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TankWeight)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankWeight)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TankVolume)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankVolume)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TankMaterial)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankMaterial)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TankPicture)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankPicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TankID" />
        <input type="submit" value="Удалить" class="btn btn-default" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

FuelStation/Views/Tanks/Details.cshtml
@model Tank

@{
    ViewData["Title"] = "Подробно";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Детально</h2>

<div>
    <h4>Емкость</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TankType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TankWeight)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankWeight)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TankVolume)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankVolume)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TankMaterial)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankMaterial)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TankPicture)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TankPicture)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TankID">Редактировать</a> |
    <a asp-action="Index">Вернуться к списку</a>
</div>

FuelStation/Views/Tanks/Edit.cshtml
@model Tank

@{
    ViewData["Title"] = "Редактировать";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактировать</h2>

<h4>Емкость</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TankID" />
            <div class="form-group">
                <label asp-for="TankType" class="control-label"></label>
                <input asp-for="TankType" class="form-control" />
                <span asp-validation-for="TankType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankWeight" class="control-label"></label>
                <input asp-for="TankWeight" class="form-control" />
                <span asp-validation-for="TankWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankVolume" class="control-label"></label>
                <input asp-for="TankVolume" class="form-control" />
                <span asp-validation-for="TankVolume" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankMaterial" class="control-label"></label>
                <input asp-for="TankMaterial" class="form-control" />
                <span asp-validation-for="TankMaterial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankPicture" class="control-label"></label>
                <input asp-for="TankPicture" class="form-control" />
                <span asp-validation-for="TankPicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FuelStation/Views/Tanks/Index.cshtml
@model TanksViewModel
@{
    ViewData["Title"] = "Емкости";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string TankType = Model.TankType;
}

<h2>Емкости</h2>

<p>
    <a asp-action="Create">Создать</a>
</p>
@using (Html.BeginForm("Index", "Tanks", FormMethod.Get))
{

    <fieldset>
        Наименование емкости: @Html.TextBox("TankType", "")

        <input type="submit" value="Найти" />

    </fieldset>


}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tanks.FirstOrDefault().TankType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tanks.FirstOrDefault().TankWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tanks.FirstOrDefault().TankVolume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tanks.FirstOrDefault().TankMaterial)
            </th>
            <th>Действие</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Tanks)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TankType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TankWeight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TankVolume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TankMaterial)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.TankID">Редактировать</a> |
                    <a asp-action="Details" asp-route-id="@item.TankID">Подробно</a> |
                    <a asp-action="Delete" asp-route-id="@item.TankID">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<page-link page-model="Model.PageViewModel" page-action="Index"
           page-url-FuelType="@TankType"
           ></page-link>